name: deploy

on: 
  push:
    branches: [main]
    
jobs:
  serverless-deploy-production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install serverless CLI
        run: npm install -g serverless
      - name: Install npm dependencies
        run: npm install
      - name: set environment variables
        run: |
          touch .env
          echo "DB_HOST=${{secrets.DB_HOST}}" >> .env
          echo "DB_USER=${{secrets.DB_USER}}" >> .env
          echo "DB_PASS=${{secrets.DB_PASS}}" >> .env 
          echo "DB_DATABASE=${{secrets.DB_DATABASE}}" >> .env 
          echo "DB_PORT=${{secrets.DB_PORT}}" >> .env 
          echo "MONGO_URL=${{secrets.MONGO_URL}}" >> .env

      - name: Test
        run: npm test
      - name: deploy
        run: |
          serverless config credentials --provider aws --key ${{secrets.AWS_ACCESS_KEY}} --secret ${{secrets.AWS_SECRET_ACCESS_KEY}}
          serverless deploy
