service: opd

frameworkVersion: '3'


provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: ap-south-1

functions:
  presriptionTest:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'