name: deploy

on:
  push:
    branches: [main]

jobs: 
  serverless-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install serverless CLI
        run: npm install -g serverless
      - name: Install npm dependencies
        run: npm install
      - name: set environment variables
        run: |
          touch .env
          echo "MONGO_URL=${{secrets.MONGO_URL}}" >> .env
      - name: Test
        run: npm test
      - name: deploy 
        run: | 
          serverless config credentials --provider aws --key ${{secrets.AWS_ACCESS_KEY}} --secret ${{secrets.AWS_SECRET_ACCESS_KEY}}
          serverless deploy